import { marked } from "marked";

function decodeUrlForSchemeCheck(value: string): string {
  let decoded = value
    .replace(/&#(\d+);?/g, (_match, code) => String.fromCodePoint(Number(code)))
    .replace(/&#x([0-9a-f]+);?/gi, (_match, code) => String.fromCodePoint(Number.parseInt(code, 16)))
    .replace(/&colon;?/gi, ":")
    .replace(/&(?:tab|newline);?/gi, "");
  for (let index = 0; index < 2; index += 1) {
    try {
      const next = decodeURIComponent(decoded);
      if (next === decoded) break;
      decoded = next;
    } catch {
      break;
    }
  }
  return Array.from(decoded)
    .filter((character) => {
      const code = character.codePointAt(0) ?? 0;
      return code > 0x20 && code !== 0x7f;
    })
    .join("")
    .toLowerCase();
}

function isSafeMarkdownUrl(value: string): boolean {
  const normalized = decodeUrlForSchemeCheck(value);
  return (
    normalized.startsWith("https://") ||
    normalized.startsWith("http://") ||
    normalized.startsWith("mailto:") ||
    normalized.startsWith("#") ||
    (normalized.startsWith("/") && !normalized.startsWith("//")) ||
    normalized.startsWith("./") ||
    normalized.startsWith("../")
  );
}

export function renderSafeMarkdown(markdown: string): string {
  // Drafts are author input. Display raw HTML as text, then only retain web-safe
  // destinations in the markup generated by marked.
  const escapedHtml = String(markdown ?? "").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  const rendered = String(marked.parse(escapedHtml, { breaks: true, gfm: true }));
  return rendered.replace(
    /\s(href|src)=(?:"([^"]*)"|'([^']*)')/gi,
    (attribute, name, doubleQuoted, singleQuoted) => {
      const value = String(doubleQuoted ?? singleQuoted ?? "");
      return isSafeMarkdownUrl(value) ? attribute : ` data-removed-${String(name).toLowerCase()}="unsafe"`;
    },
  );
}
