// tools/src/goBuild.ts
import fs from 'node:fs';
import path from 'node:path';
import { readJSON, writeFileEnsure } from './utils';

export function goBuild() {
  const CWD = process.cwd();
  const CONTENT_DIR = path.join(CWD, 'content');
  const PUBLIC_DIR = path.join(CWD, 'public');
  const PAGES_GO_DIR = path.join(CWD, 'src', 'pages', 'go');

  const productsJson = readJSON(path.join(CONTENT_DIR, 'products.json')) || { products: [] };
  const products: Array<{ key?: string; url?: string; utm?: string }> =
    Array.isArray(productsJson.products) ? productsJson.products : [];

  // Ensure dirs exist (writeFileEnsure also creates parents, but we want explicit clarity)
  fs.mkdirSync(PUBLIC_DIR, { recursive: true });
  fs.mkdirSync(PAGES_GO_DIR, { recursive: true });

  // Build Netlify _redirects lines
  const lines: string[] = [];
  for (const p of products) {
    const key = safeKey(p.key);
    if (!key) continue;
    if (!p.url) continue; // no redirect if no target

    const target = appendUtm(p.url, p.utm);
    lines.push(`/go/${key} ${target} 301!`);
  }

  const redirectsPath = path.join(PUBLIC_DIR, '_redirects');
  const redirectsContent = (lines.join('\n') + (lines.length ? '\n' : ''));
  writeFileEnsure(redirectsPath, redirectsContent);

  // Fallback Astro pages (meta refresh)
  for (const p of products) {
    const key = safeKey(p.key);
    if (!key) continue;

    const url = p.url ? appendUtm(p.url, p.utm) : '';
    const file = `---
// NOTE: auto-generated by goBuild.ts
import Base from '../../layouts/Base.astro';
---
<Base title="Redirecting…" description="Taking you to the resource.">
  <Fragment slot="head">
    ${url ? `<meta http-equiv="refresh" content="0;url=${escapeAttr(url)}" />` : ''}
    <noscript><meta http-equiv="refresh" content="0;url=/"/></noscript>
    <script>try{${url ? `location.replace(${JSON.stringify(url)});` : ''}}catch{}</script>
  </Fragment>
  <p>Redirecting…${url ? '' : ' (No URL configured.)'}</p>
</Base>
`;
    const outPath = path.join(PAGES_GO_DIR, `${key}.astro`);
    writeFileEnsure(outPath, file);
  }

  process.stdout.write(
    `Built ${lines.length} Netlify redirects → ${redirectsPath}\n` +
    `Generated ${products.length} fallback page(s) in /src/pages/go\n`
  );
}

function safeKey(v?: string) {
  if (!v) return '';
  return String(v).trim().toLowerCase().replace(/[^a-z0-9-]/g, '-').replace(/--+/g, '-');
}

function appendUtm(url: string, utm?: string) {
  if (!utm) return url;
  try {
    const u = new URL(url);
    const extra = new URLSearchParams(utm.startsWith('?') ? utm.slice(1) : utm);
    for (const [k, v] of extra.entries()) u.searchParams.set(k, v);
    return u.toString();
  } catch {
    // fallback: naive concat without double "?"
    const sep = url.includes('?') ? '&' : '?';
    return url + sep + utm.replace(/^\?/, '');
  }
}

function escapeAttr(s: string) {
  return String(s).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');
}
