// src/utils/entities.js — no TypeScript syntax, ESM only
import fs from 'node:fs';
import path from 'node:path';

const CONTENT_ROOT = path.join(process.cwd(), 'content', 'entities');
const UNPUBLISHED_STATUSES = new Set(['draft', 'stub', 'placeholder', 'pending', 'wip']);
const STUB_TEXT_PATTERN = /\b(stub|placeholder)\b/i;

function asString(value) {
  return typeof value === 'string' ? value.trim() : '';
}

function asProperties(value) {
  if (value && typeof value === 'object' && !Array.isArray(value)) {
    return value;
  }
  return {};
}

function asRelated(value) {
  if (!Array.isArray(value)) return [];
  return value
    .map((entry) => (typeof entry === 'string' ? entry.trim() : ''))
    .filter(Boolean);
}

function normalizeStatus(value) {
  return asString(value).toLowerCase();
}

function normalizeEntityRecord(raw, fallbackType, fallbackSlug) {
  const source = raw && typeof raw === 'object' ? raw : {};
  const type = asString(source.type) || fallbackType;
  const slug = asString(source.slug) || fallbackSlug;
  const name = asString(source.name) || slug;
  const summary = asString(source.summary);
  const properties = asProperties(source.properties);
  const related = asRelated(source.related);

  const status = normalizeStatus(source.status);
  const explicitDraft = source.draft === true || source.published === false;
  const explicitStub = source.stub === true || source.autoGenerated === true;
  const statusStub = status ? UNPUBLISHED_STATUSES.has(status) : false;
  const summaryStub = STUB_TEXT_PATTERN.test(summary);
  const isStub = Boolean(explicitDraft || explicitStub || statusStub || summaryStub);
  const published = !isStub;

  return {
    type,
    slug,
    name,
    summary,
    properties,
    related,
    isStub,
    published,
  };
}

export function isEntityStub(record) {
  if (!record || typeof record !== 'object') return true;
  return normalizeEntityRecord(record, asString(record.type), asString(record.slug)).isStub;
}

export function isEntityPublished(record) {
  return !isEntityStub(record);
}

export function readAllEntities(options = {}) {
  const includeUnpublished = options.includeUnpublished === true;
  const result = {};
  if (!fs.existsSync(CONTENT_ROOT)) return result;

  const types = fs.readdirSync(CONTENT_ROOT, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name);

  for (const type of types) {
    const dir = path.join(CONTENT_ROOT, type);
    const files = fs.readdirSync(dir).filter((f) => f.endsWith('.json'));
    const items = [];
    for (const f of files) {
      try {
        const j = JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8'));
        const slug = f.replace(/\.json$/, '');
        const record = normalizeEntityRecord(j, type, slug);
        if (!includeUnpublished && !record.published) continue;
        items.push(record);
      } catch {
        // ignore malformed JSON files
      }
    }
    items.sort((a, b) => a.name.localeCompare(b.name));
    result[type] = items;
  }
  return result;
}

export function readEntity(type, slug, options = {}) {
  const includeUnpublished = options.includeUnpublished === true;
  const file = path.join(CONTENT_ROOT, type, `${slug}.json`);
  if (!fs.existsSync(file)) return null;
  try {
    const j = JSON.parse(fs.readFileSync(file, 'utf8'));
    const record = normalizeEntityRecord(j, type, slug);
    if (!includeUnpublished && !record.published) return null;
    return record;
  } catch {
    return null;
  }
}
