export const STRICT_JSON_RULES = [
  'STRICT JSON OUTPUT RULES (do all of these):',
  '• Output a single JSON object. No markdown fences. No preface/suffix text.',
  '• Use straight quotes ("). Never use “smart quotes”.',
  '•Inside all markdown strings, avoid unescaped double quotes; prefer single quotes or escape like \\" within JSON strings.',
  '• Do not escape brackets/braces unless inside strings: never emit \\[ or \\{ in the top-level structure.',
  '• No trailing commas. No comments. No undefined. Use [] for empty arrays and "" for empty strings. heroImagePrompt may be null.',
  '• CRITICAL - externalLink format rules: "url" must be a plain URL string ONLY.',
  '• Never combine url and anchor into one string, never use markdown link syntax in the url field, and never wrap the url in brackets or parentheses.',
  '• "anchor" and "url" are always separate fields.',
  '• Valid: {"url": "https://example.com", "anchor": "text here", "description": "..."}',
  '• Invalid: {"url": "[text here](https://example.com)", ...}',
  '• Invalid: {"url": "https://example.com%22,%22anchor%22:%22text", ...}',
  '• If you cannot produce a clean url string, omit externalLink entirely rather than malforming it.',
  '• Never include a "sourceNote" field in the output.',
  '• sourceNote is an internal LLM artifact and must not appear in the JSON.',
  '• Start your response with "{" and end with "}".',
  '• Self-check before sending: imagine running JSON.parse on your answer. If it would fail, correct and re-emit the entire object.',
  '',
  'GOLDEN JSON EXAMPLE (minimally valid shape — copy the structure, not the content):',
  '{"specVersion":2,"title":"t","slug":"t","metaDescription":"t","tags":["a","b","c","d"],"excerpt":"t","outline":[{"heading":"Opening Reflection","id":"opening-reflection"}],"sections":[{"heading":"Opening Reflection","markdown":"M"}],"entities":[],"heroImagePrompt":null,"altTexts":[],"internalLinkHints":[{"anchor":"a","rationale":"r"}],"affiliateHints":[{"key":"ritual-journal","anchor":"a","rationale":"r"}],"cta":{"type":"none"},"adPlacements":[]}',
  '',
  'GOLDEN JSON EXAMPLE (no relevant affiliates despite allowed keys):',
  '{',
  '  "specVersion":2,',
  '  "title":"Grounding Breath Break Ritual",',
  '  "slug":"grounding-breath-break-ritual",',
  '  "metaDescription":"Reset with a mindful breathwork pause that calms your nervous system gently.",',
  '  "tags":["breathwork","mindfulness","self-care","grounding"],',
  '  "excerpt":"Pause for a grounding breath ritual with quick and deep pathways.",',
  '  "outline":[{"heading":"Opening Reflection","id":"opening-reflection"},{"heading":"Quick Breath Break Variant","id":"quick-breath-break-variant"},{"heading":"Deep Breath Break Variant","id":"deep-breath-break-variant"},{"heading":"Reflection Prompt","id":"reflection-prompt"},{"heading":"Breath Break Checklist","id":"breath-break-checklist"}],',
  '  "sections":[{"heading":"Opening Reflection","markdown":"Two short grounding paragraphs..."},{"heading":"Quick Breath Break Variant","markdown":"1. Step one..."},{"heading":"Deep Breath Break Variant","markdown":"1. Step one..."},{"heading":"Reflection Prompt","markdown":"### Reflection Prompt\\nWhat sensation shifted as you breathed?"},{"heading":"Breath Break Checklist","markdown":"- Item one"}],',
  '  "entities":[], "heroImagePrompt":null, "altTexts":[],',
  '  "internalLinkHints":[{"anchor":"mindful breathing","rationale":"Link to existing breathwork explainer."}],',
  '  "affiliateHints":[],',
  '  "cta":{"type":"none"},',
  '  "adPlacements":["mid"]',
  '}'
];

export default STRICT_JSON_RULES;
